Proy/Proy/Proy/Proy/urls.py
"""
Definition of urls for Proy.
"""

from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from django.contrib import admin
from cuentas.views import ConsultaUltimosMovView, ConsultaDeudasView, UserDeleteView, CtaCteDeleteView, CtaCteDetailsView, CtaCteUpdateView, CtaCteMenuView, UserMenuView, UserUpdateView, UserRegistrationView, HomeView, TemplateView, NewCuentaCorrienteView


urlpatterns = [
    #url(r'^$', TemplateView.as_view(template_name='base.html'),name='home'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^menu-user/$', UserMenuView.as_view(), name='menu_usr'),
    url(r'^menu-ctacte/$', CtaCteMenuView.as_view(), name='menu_ctacte'),
    url(r'^new-user/$', UserRegistrationView.as_view(), name='user_registration' ),
    url(r'^update-user/(?P<pk>\d+)/$', UserUpdateView.as_view(), name='user_update'),
    url(r'^eliminar/(?P<pk>\d+)/$', UserDeleteView.as_view(), name='user_delete'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/login/'}, name= 'logout'),
    url(r'^nuevo-mov/$', NewCuentaCorrienteView.as_view(), name='nuevo_movimiento' ),
    url(r'^update-ctacte/(?P<pk>\d+)/$', CtaCteUpdateView.as_view(), name='ctacte_update'),
    url(r'^(?P<pk>\d+)/$', CtaCteDetailsView.as_view(),name='ctacte_detalle'),
    url(r'^eliminar/(?P<pk>\d+)/$', CtaCteDeleteView.as_view(), name='ctacte_delete'),
    url(r'^consulta-deudas/$', ConsultaDeudasView.as_view(), name='consulta_deuda' ),
    url(r'^ultimos_movimientos/$', ConsultaUltimosMovView.as_view(), name='consulta_ultimos'),
    url(r'^admin/', include(admin.site.urls)),
]

Proy/Proy/Proy/urls.py
"""
Definition of urls for Proy.
"""

from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from django.contrib import admin
from cuentas.views import SetPasswordView, ConsultaUltimosMovView, ConsultaDeudasView, UserDeleteView, CtaCteDeleteView, CtaCteDetailsView, CtaCteUpdateView, CtaCteMenuView, UserMenuView, UserUpdateView, UserRegistrationView, HomeView, TemplateView, NewCuentaCorrienteView
from cuentas import views

urlpatterns = [
    #url(r'^$', TemplateView.as_view(template_name='base.html'),name='home'),
    url(r'^home/$', HomeView.as_view(), name='home'),
    url(r'^menu-user/$', UserMenuView.as_view(), name='menu_usr'),
    url(r'^menu-ctacte/$', CtaCteMenuView.as_view(), name='menu_ctacte'),
    url(r'^new-user/$', UserRegistrationView.as_view(), name='user_registration' ),
    url(r'^update-user/(?P<pk>\d+)/$', UserUpdateView.as_view(), name='user_update'),
    url(r'password/$', SetPasswordView.as_view(), name='change_password'),
    url(r'^eliminar-usr/(?P<pk>\d+)/$', UserDeleteView.as_view(), name='user_delete'),
    url(r'^$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name= 'logout'),
    url(r'^nuevo-mov/$', NewCuentaCorrienteView.as_view(), name='nuevo_movimiento' ),
    url(r'^update-ctacte/(?P<pk>\d+)/$', CtaCteUpdateView.as_view(), name='ctacte_update'),
    url(r'^(?P<pk>\d+)/$', CtaCteDetailsView.as_view(),name='ctacte_detalle'),
    url(r'^eliminar-ctacte/(?P<pk>\d+)/$', CtaCteDeleteView.as_view(), name='ctacte_delete'),
    url(r'^consulta-deudas/$', ConsultaDeudasView.as_view(), name='consulta_deuda' ),
    url(r'^ultimos_movimientos/$', ConsultaUltimosMovView.as_view(), name='consulta_ultimos'),
    url(r'^admin/', include(admin.site.urls)),
]

Proy/Proy/Proy/cuentas/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class usuarios(AbstractUser):
    administrativo= 'A'
    cliente='I'
    tipo_opciones=(
        (administrativo, 'Administrador'),
        (cliente,'Inquilino'),
        )
    passtxt=models.CharField(max_length=45)
    tipoUsr=models.CharField(max_length=15,
                             choices=tipo_opciones,
                             default=administrativo,)
    
       

class ctacte(models.Model):
    inquilino=models.ForeignKey(usuarios)
    detalle=models.CharField(max_length=200)
    importe=models.CharField(max_length=15)
    fecha= models.DateField(auto_now_add=True)  
    concepto= models.CharField(max_length=10)
    saldo= models.CharField(max_length=15, blank=True)
    factura=models.CharField(max_length=15, blank=True)
    sociedad= models.CharField(max_length=10, blank=True)

Proy/Proy/cuentas/models.py
from django.db import models, connections
from django.contrib.auth.models import AbstractUser

class usuarios(AbstractUser):
    administrativo= 'A'
    cliente='I'
    tipo_opciones=(
        (administrativo, 'Administrador'),
        (cliente,'Inquilino'),
        )
    password=models.BinaryField()
    passtxt=models.CharField(max_length=45)
    tipoUsr=models.CharField(max_length=15,
                             choices=tipo_opciones,
                             default=administrativo,)
    nro_inquilino=models.IntegerField(null=True,blank=True, unique=True)

    def check_password(self, password):
       cur = connections['default'].cursor()
       res=cur.callproc("sp_login", [self.username, password, 0,0])
       cur.close()
       if res[0]!='F' and res[1]!='-1':
           return True
    
    
    
       

class ctacte(models.Model):
    nro_inquilino=models.IntegerField(null=True,blank=True, unique=True)
    detalle=models.CharField(max_length=200)
    importe=models.CharField(max_length=15)
    fecha= models.DateField(auto_now_add=True)  
    concepto= models.CharField(max_length=10)
    saldo= models.CharField(max_length=15, blank=True)
    factura=models.CharField(max_length=15, blank=True)
    sociedad= models.CharField(max_length=10, blank=True)

Proy/Proy/Proy/cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import usuarios, ctacte

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = usuarios
        fields = ('username', 'tipoUsr')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = usuarios
        fields = ('username', 'tipoUsr')
    def clean_password(self):
        password = self.cleaned_data.get('password')
        
        

class CuentaCorrienteForm(forms.ModelForm):
    def __init__(self,*arg,**kwargs):
        super(CuentaCorrienteForm, self).__init__(*arg, **kwargs)
        self.fields['inquilino'].queryset= usuarios.objects.filter(tipoUsr='I')
    
    class Meta:
        model= ctacte
        fields='__all__'
        

Proy/Proy/cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from .models import usuarios, ctacte


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=usuarios
        fields=('username','first_name', 'tipoUsr', 'nro_inquilino')


class CustomUserChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField(label= ("Contraseña"),
                help_text= ("Para cambiar la contraseña utiliza <a href=\"/password/\">este formulario</a>."))
                   
    class Meta:
        model = usuarios
        fields = ('username', 'tipoUsr')

    def clean_password(self):
        password = self.cleaned_data.get('password')

        
        

class CuentaCorrienteForm(forms.ModelForm):
    def __init__(self,*arg,**kwargs):
        super(CuentaCorrienteForm, self).__init__(*arg, **kwargs)
        inq= usuarios.objects.filter(tipoUsr='I')
        self.fields['nro_inquilino'].queryset=inq
    class Meta:
        model= ctacte
        fields='__all__'
        

Proy/Proy/Proy/cuentas/views.py
from django.shortcuts import render
from .models import usuarios, ctacte
from django.http.response import HttpResponseRedirect
from .forms import CustomUserChangeForm, CustomUserCreationForm, CuentaCorrienteForm
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import DeleteView, DetailView, View, CreateView, TemplateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta

class HomeView(TemplateView):
    template_name='home.html'

    def get_context_data(self, **kwargs):
        ctx = super(HomeView, self).get_context_data(**kwargs)
        
        if self.request.user.is_authenticated():
            if self.request.user.tipoUsr=='I':
                ctx['es_cliente']=True

        return ctx

class UserMenuView(TemplateView):
    template_name='menu_usr.html'
    
    def get_context_data(self, **kwargs):
        con = super(UserMenuView, self).get_context_data(**kwargs)
        
        if self.request.user.is_authenticated():  
            con['usuarios']=usuarios.objects.filter(tipoUsr='I')
        
        return con

class UserRegistrationView(CreateView):
    form_class= CustomUserCreationForm
    template_name='user.html'

    def get_success_url(self):
        return reverse('home')

class UserUpdateView(UpdateView):
    form_class= CustomUserChangeForm
    template_name='user.html'
    success_url='/'
    model=usuarios

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UserUpdateView, self).dispatch(request, *args, **kwargs)

class UserDeleteView(DeleteView):
    model= usuarios
    template_name='confirmacion.html'
    success_url= reverse_lazy('menu_usr')
class CtaCteMenuView(TemplateView):
    template_name='menu_ctacte.html'
    
    def get_context_data(self, **kwargs):
        ctd = super(CtaCteMenuView, self).get_context_data(**kwargs)
        
        if self.request.user.is_authenticated():  
            ctd['ctactes']=ctacte.objects.all()
        
        return ctd


class NewCuentaCorrienteView(CreateView):
        form_class = CuentaCorrienteForm
        template_name = 'cuenta_corriente.html'
        
        def form_valid(self, form):
            ctacte_obj= form.save(commit=False)
            ctacte_obj.saldo= ctacte_obj.importe
            ctacte_obj.save()
            return HttpResponseRedirect(reverse('home'))

        @method_decorator(login_required)
        def dispatch(self, request, *args, **kwargs):
            return super(NewCuentaCorrienteView, self).dispatch(request, *args,**kwargs)
 

class CtaCteUpdateView(UpdateView):
    form_class= CuentaCorrienteForm
    template_name='cuenta_corriente.html'
    success_url='/'
    model=ctacte

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CtaCteUpdateView, self).dispatch(request, *args, **kwargs)

class CtaCteDetailsView(DetailView):
    model= ctacte
    template_name= 'detalle_ctacte.html'

class CtaCteDeleteView(DeleteView):
    model= ctacte
    template_name='confirmacion.html'
    success_url= reverse_lazy('menu_ctacte')

class ConsultaDeudasView(TemplateView):
    template_name='consulta_deudas.html'

    @method_decorator(login_required)
    def dispatch(self, request, *arg, **kwargs):
        return super(ConsultaDeudasView, self).dispatch(request, *arg, **kwargs)

    def get_context_data(self, **kwargs):
        cdt = super(ConsultaDeudasView, self).get_context_data(**kwargs)
        
        if self.request.user.is_authenticated():
            cdt['deudas']=ctacte.objects.filter(inquilino=self.request.user).filter(saldo__gt=0)
        return cdt

class ConsultaUltimosMovView(TemplateView):
    template_name='consulta_ultimos.html'

    @method_decorator(login_required)
    def dispatch(self, request, *arg, **kwargs):
        return super(ConsultaUltimosMovView, self).dispatch(request, *arg, **kwargs)

    def get_context_data(self, **kwargs):
        cot = super(ConsultaUltimosMovView, self).get_context_data(**kwargs)
        
        tresMeses= datetime.today()- timedelta(days=90)
        if self.request.user.is_authenticated():
            cot['ultimos']=ctacte.objects.filter(inquilino=self.request.user).filter(fecha__gte=tresMeses)
        return cot

Proy/Proy/cuentas/views.py
from django.shortcuts import render, redirect
from .models import usuarios, ctacte
from django.http.response import HttpResponseRedirect
from .forms import CustomUserChangeForm, CustomUserCreationForm, CuentaCorrienteForm
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import DeleteView, DetailView, View, CreateView, TemplateView, UpdateView, FormView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, AdminPasswordChangeForm


class HomeView(TemplateView):
    template_name='home.html'

    def get_context_data(self, **kwargs):
        ctx = super(HomeView, self).get_context_data(**kwargs)
        
        if self.request.user.is_authenticated():
            if self.request.user.tipoUsr=='I':
                ctx['es_cliente']=True

        return ctx

class UserMenuView(TemplateView):
    template_name='menu_usr.html'
    
    def get_context_data(self, **kwargs):
        con = super(UserMenuView, self).get_context_data(**kwargs)
        
        if self.request.user.is_authenticated():  
            con['usuarios']=usuarios.objects.filter(tipoUsr='I')
        
        return con

class UserRegistrationView(CreateView):
    form_class= CustomUserCreationForm
    template_name='user.html'

    def form_valid(self, form):
            usr_obj= form.save(commit=False)
            if usr_obj.tipoUsr=='I':
                usr_obj.nro_inquilino= usr_obj.id
            usr_obj.save()
            return HttpResponseRedirect(reverse('home'))

    def get_success_url(self):
        return reverse('home')


class UserUpdateView(UpdateView):
    form_class= CustomUserChangeForm
    template_name='userUD.html'
    success_url='/'
    model=usuarios

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UserUpdateView, self).dispatch(request, *args, **kwargs)



class SetPasswordView(FormView):

    form_class = AdminPasswordChangeForm
    template_name = 'change-password.html'
    success_url = 'home'

    def get_form_kwargs(self):
        kwargs = super(set, self).get_form_kwargs()
        kwargs['user_to_update'] = user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(SetPasswordView, self).form_valid(form)

class UserDeleteView(DeleteView):
    model= usuarios
    template_name='confirmacion.html'
    success_url= reverse_lazy('home')

class CtaCteMenuView(TemplateView):
    template_name='menu_ctacte.html'
    
    def get_context_data(self, **kwargs):
        ctd = super(CtaCteMenuView, self).get_context_data(**kwargs)
        
        if self.request.user.is_authenticated():  
            ctd['ctactes']=ctacte.objects.all().order_by('-fecha')
        
        return ctd


class NewCuentaCorrienteView(CreateView):
        form_class = CuentaCorrienteForm
        template_name = 'cuenta_corriente.html'
        
        def form_valid(self, form):
            ctacte_obj= form.save(commit=False)
            ctacte_obj.saldo= ctacte_obj.importe
            ctacte_obj.save()
            return HttpResponseRedirect(reverse('home'))

        @method_decorator(login_required)
        def dispatch(self, request, *args, **kwargs):
            return super(NewCuentaCorrienteView, self).dispatch(request, *args,**kwargs)
 

class CtaCteUpdateView(UpdateView):
    form_class= CuentaCorrienteForm
    template_name='cuenta_corriente.html'
    success_url='/'
    model=ctacte

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CtaCteUpdateView, self).dispatch(request, *args, **kwargs)

class CtaCteDetailsView(DetailView):
    model= ctacte
    template_name= 'detalle_ctacte.html'

class CtaCteDeleteView(DeleteView):
    model= ctacte
    template_name='confirmacion-ctacte.html'
    success_url= reverse_lazy('home')

class ConsultaDeudasView(TemplateView):
    template_name='consulta_deudas.html'

    @method_decorator(login_required)
    def dispatch(self, request, *arg, **kwargs):
        return super(ConsultaDeudasView, self).dispatch(request, *arg, **kwargs)

    def get_context_data(self, **kwargs):
        cdt = super(ConsultaDeudasView, self).get_context_data(**kwargs)
        
        if self.request.user.is_authenticated():
            cdt['deudas']=ctacte.objects.filter(nro_inquilino=self.request.user.nro_inquilino).exclude(saldo__exact="0.00").order_by('-fecha')
        return cdt

class ConsultaUltimosMovView(TemplateView):
    template_name='consulta_ultimos.html'

    @method_decorator(login_required)
    def dispatch(self, request, *arg, **kwargs):
        return super(ConsultaUltimosMovView, self).dispatch(request, *arg, **kwargs)

    def get_context_data(self, **kwargs):
        cot = super(ConsultaUltimosMovView, self).get_context_data(**kwargs)
        
        tresMeses= datetime.today()- timedelta(days=90)
        if self.request.user.is_authenticated():
            cot['ultimos']=ctacte.objects.filter(nro_inquilino=self.request.user.nro_inquilino).filter(fecha__gte=tresMeses).order_by('-fecha')
        return cot

Proy/Proy/cuentas/templates/base.html
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ValeriaSA</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'content/site.css' %}" />
    <script src="{% static 'scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                
                <a href="/" class="navbar-brand">ValeriaSA</a>
            </div>
            <div class="navbar-collapse collapse">
                
                 {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                <li><span class="navbar-brand">Bienvenido {% if user.first_name %} {{ user.first_name }} {% else %} {{user.username}} {%endif%}</span></li>
                <li><a href="{% url "logout" %}">Salir</a></li>
                    </ul>

                {% else %}
                <META HTTP-EQUIV="REFRESH" CONTENT="0;URL=login">
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block content %}{% endblock %}
        
    </div>

    <script src="{% static 'scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'scripts/bootstrap.js' %}"></script>
    <script src="{% static 'scripts/respond.js' %}"></script>
    {% block scripts %}{% endblock %}

</body>
    
</html>

Proy/Proy/cuentas/templates/change_password.html
{% extends "base.html" %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>

{% endblock %}

Proy/Proy/cuentas/templates/confirmacion-ctacte.html
{% extends "base.html" %}
{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Estas seguro que quieres eliminar elemento "{{ object.pk }}"?</p>
    <input type="submit" value="Confirmar" />
</form>
{% endblock %}

Proy/Proy/cuentas/templates/confirmacion.html
{% extends "base.html" %}
{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Estas seguro que quieres eliminar al usuario "{{ object.username }}"?</p>
    <input type="submit" value="Confirmar" />
</form>
{% endblock %}

Proy/Proy/cuentas/templates/consulta_deudas.html
{% extends "base.html" %}
{% block content %}
<h3>Saldos Pendientes</h3>
<hr />
<table cellpadding="5" cellspacing="3">
    {% if deudas %}
    <tr>
        <th>Fecha</th><th>Descripci&oacute;n</th><th>Importe</th><th>Saldo</th>
    </tr>
    {% for cc in deudas %}
    <tr>
    <td>{{cc.fecha}}</td> <td>{{cc.detalle}}</td> <td>{{cc.importe}} </td> <td>{{cc.saldo}} </td> 
    </tr>
    {% endfor %}
    {% else %}
    No hay deudas pendientes
    {%endif%}
</table>
<br />
<input type="button" value="Volver" onclick="history.back()" class="boton">
{% endblock %}

Proy/Proy/cuentas/templates/consulta_ultimos.html
{% extends "base.html" %}
{% block content %}
<h3>Ultimos Movimientos</h3>
<hr />
 {% if ultimos %}
<table cellpadding="5" cellspacing="3">
   
    <tr>
        <th>Fecha</th><th>Descripci&oacute;n</th><th>Importe</th><th>Saldo</th>
    </tr>
    {% for cc in ultimos %}
    <tr>
    <td>{{cc.fecha}}</td> <td>{{cc.detalle}}</td> <td>{{cc.importe}} </td> <td>{{cc.saldo}} </td> 
    </tr>
    {% endfor %}

    {% else %}
    No hay movimientos en los &uacute;ltimos tres meses
    {% endif %}
    
</table>
<br />
<br />
<input type="button" value="Volver" onclick="history.back()" class="boton">
    


{% endblock %}

Proy/Proy/cuentas/templates/cuenta_corriente.html
{% extends "base.html" %}
{% block content %}
<h3> {% if object %}Editar {% else %} Crear Nuevo {% endif %} registro </h3>

<div class="row">
    <div class="col-md-8">
        <section id="create-form">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_inquilino" class="col-md-2 control-label">Inquilino</label>
                    <div class="col-md-10">
                        {{ form.nro_inquilino }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_detalle" class="col-md-2 control-label">Detalle</label>
                    <div class="col-md-10">
                        {{ form.detalle }}
                    </div>
                </div>

                
                <div class="form-group">
                    <label for="id_importe" class="col-md-2 control-label">Importe</label>
                    <div class="col-md-10">
                        {{ form.importe }}
                    </div>
                </div>
                
                
                <div class="form-group">
                    <label for="id_concepto" class="col-md-2 control-label">Concepto</label>
                    <div class="col-md-10">
                        {{ form.concepto }}
                    </div>
                </div>
                
                
                <div class="form-group">
                    <label for="id_saldo" class="col-md-2 control-label" >Saldo</label>
                    <div class="col-md-10">
                        {{ form.saldo }}
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_factura" class="col-md-2 control-label">Factura</label>
                    <div class="col-md-10">
                        {{ form.factura }}
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_sociedad" class="col-md-2 control-label">Sociedad</label>
                    <div class="col-md-10">
                        {{ form.sociedad }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        
                        <input type="submit" value="Aceptar" class="boton" />
                    </div>
                </div>
                
            </form>
        </section>
    </div>
    
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

Proy/Proy/cuentas/templates/detalle_ctacte.html
{% extends "base.html" %}
{% block content %}
<h3>Nombre de Usuario: {{ object.nro_inquilino }}</h3>
<p>Id: {{object.pk}}</p>
<p>Detalle: {{ object.detalle }}</p>
<p>Importe: {{ object.importe }}</p>
<p>Fecha: {{ object.fecha }}</p>
<p>Concepto: {{ object.concepto }}</p>
<p>Saldo: {{ object.saldo }}</p>
<p>Factura: {{ object.factura }}</p>
<p>Sociedad: {{ object.sociedad }}</p>

<br />
<input type="button" value="Volver" onclick="history.back()" class="boton">
{% endblock %}

 

Proy/Proy/cuentas/templates/home.html
{% extends "base.html" %}
{% block content %}

<div id="menu">
{% if es_cliente %}
    <ul>
    <li><a href="{% url "consulta_deuda" %}">Consultar Saldos Pendientes</a></li>
    <li><a href="{% url "consulta_ultimos" %}">Consultar Ultimos Movimientos</a></li>
    <li><a >Descargar Cup&oacute;n</a></li>
    </ul>
{% else %}
<ul>
    <li><a href="{% url "menu_usr"%}">Menu Clientes</a></li>
    <li><a href="{% url "menu_ctacte"%}">Menu Cuentas Corrientes</a></li>
    
</ul>
{% endif %}

</div>

{% endblock %}

Proy/Proy/cuentas/templates/menu_ctacte.html
{% extends "base.html" %}
{% block content %}
<h3>Menu Cuentas Corrientes</h3>
<hr />
    <li><a href="{% url "nuevo_movimiento"%}">Crear nuevo Movimiento</a></li>
<h3>Listado</h3>
<hr />
<table cellpadding="5" cellspacing="3">

    <tr>
        <th>Inquilino</th><th>Descripci&oacute;n</th><th>Fecha</th><th>Detalle</th><th>Modificar</th><th>Eliminar</th>
    </tr>
    {% for cc in ctactes %}
    <tr>
    <td>{{cc.nro_inquilino}}</td><td>{{ cc.detalle }}</td><td> {{cc.fecha}} </td>
    <td style="text-align: center;"><a href="{% url "ctacte_detalle" pk=cc.pk %}"> – </a></td>
    <td style="text-align: center;"><a href="{% url "ctacte_update" pk=cc.pk %}">– </a></td>
        <td style="text-align: center;"><a href="{% url "ctacte_delete" pk=cc.pk %}"> – </a></td>
    </tr>
    {% endfor %}
</table>

<br />
<input type="button" value="Volver" onclick="history.back()" class="boton">
{% endblock %}

Proy/Proy/cuentas/templates/menu_usr.html
{% extends "base.html" %}
{% block content %}
<h3>Menu Clientes</h3>
<hr />
<ul>
    <li><a href="{% url "user_registration"%}">Crear nuevo Cliente</a></li>
</ul>
<h3>Listado</h3>
<hr />
<table cellpadding="5" cellspacing="3">
   
    {% for usr in usuarios %}
    <tr>
        <td>{{usr.username}} </td>
        <td><a href="{% url "user_update" pk=usr.pk %}">Modificar</a> </td>
        <td><a href="{% url "user_delete" pk=usr.pk %}"> Eliminar </a> </td>
    </tr>
    {% endfor %}
</table>

<br />
<input type="button" value="Volver" onclick="history.back()" class="boton">
{% endblock %}